[package]
name = "spoify-tui"
version = "0.1.0"
edition = "2021"
src = ["src/**/*.rs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
ratatui = "0.26.1"
tui = "0.19.0"
tui-widget-list = "0.8.2"
